apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mockbank-svc
  name: mockbank-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockbank-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mockbank-svc
    spec:
      containers:
        - image: learn/mockbank:1.0
          name: mockbank
          resources: {}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: P@ssw0rd
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgressql:5432/postgres?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mockbank-svc
  name: mockbank-svc
spec:
  ports:
    - name: 8091-8091
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: mockbank-svc
  type: NodePort
status:
  loadBalancer: {}
