server:
  port: 9112
spring:
  zipkin:
    base_url: http://localhost:9411
    senders:
      type: web
  sleuth:
    sampler:
      probability: 1
  application:
    name: gatewayapp
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: authentication
          uri: http://localhost:8999
          predicates:
#            - Path=/authentication
            - Method=GET,POST

